#!/bin/bash
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/0-main.c 0-print_list.c _putchar.c -o tests/app-0
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/1-main.c 1-list_len.c _putchar.c -o tests/app-1
