#!/bin/bash
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/0-main.c 0-print_list.c utils.c -o tests/app-0
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/1-main.c 1-list_len.c utils.c -o tests/app-1
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/2-main.c 2-add_node.c 0-print_list.c -o tests/app-2
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 tests/3-main.c 3-add_node_end.c 0-print_list.c -o tests/app-3
